[CmdletBinding()]
param()
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$pluginRoot=Split-Path -Parent $PSScriptRoot;$dashboard=Join-Path $pluginRoot 'scripts\Get-PowerShellWorkbenchStatusDashboard.ps1';$utf8=New-Object Text.UTF8Encoding($false);$tempRoot=Join-Path ([IO.Path]::GetTempPath()) ('powershell-workbench-status-'+[guid]::NewGuid().ToString('N'))
function Assert-True{param([bool]$Condition,[string]$Message)if(-not$Condition){throw $Message}}
function Assert-GatesExactly{param($Result,[string[]]$Expected,[string]$Message)$actual=@($Result.FailedGates);if(($actual-join'|')-cne($Expected-join'|')){throw "$Message Expected [$($Expected-join', ')], got [$($actual-join', ')]."}}
function Write-Json{param([string]$LiteralPath,$Value)[IO.File]::WriteAllText($LiteralPath,($Value|ConvertTo-Json -Depth 10),$utf8)}
function Get-Sha{param([string]$LiteralPath)(Get-FileHash -LiteralPath $LiteralPath -Algorithm SHA256).Hash.ToLowerInvariant()}
function Initialize-Plugin{param([string]$Name)$root=Join-Path $tempRoot $Name;New-Item -ItemType Directory -Path (Join-Path $root '.codex-plugin'),(Join-Path $root 'scripts') -Force|Out-Null;Write-Json -LiteralPath (Join-Path $root '.codex-plugin\plugin.json') -Value ([ordered]@{name='powershell-workbench';version='0.7.9'});[IO.File]::WriteAllText((Join-Path $root 'scripts\fixture.ps1'),"'fixture'",$utf8);$root}
$tokens=$null;$errors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($dashboard,[ref]$tokens,[ref]$errors);Assert-True ($errors.Count-eq 0) 'Dashboard has parser errors.';$commands=@($ast.FindAll({param($node)$node-is[Management.Automation.Language.CommandAst]},$true)|ForEach-Object{$_.GetCommandName()}|Where-Object{$_});foreach($forbidden in @('Start-Process','Invoke-Expression','Invoke-RestMethod','Invoke-WebRequest','Set-Content','Add-Content','Out-File','Set-Clipboard','git','gh')){Assert-True ($commands-notcontains$forbidden) "Dashboard contains forbidden command $forbidden."}
try{
    New-Item -ItemType Directory -Path $tempRoot|Out-Null;$source=Initialize-Plugin source;$cache=Join-Path $tempRoot 'cache';Copy-Item -LiteralPath $source -Destination $cache -Recurse;$distribution=[pscustomobject]@{Name='personal';SourcePath=$source;CachePath=$cache}
    $health=& (Join-Path $pluginRoot 'scripts\Test-PowerShellWorkbenchHealth.ps1') -Distribution $distribution -ExpectedVersion '0.7.9' -NoThrow;$tree=$health.Distributions[0].SourceTreeSha256
    $provenancePath=Join-Path $tempRoot 'release.json';$provenance=[ordered]@{schemaVersion='1.0';pluginName='powershell-workbench';pluginVersion='0.7.9';commitSha='a'*40;sourceRef='feature/status-dashboard-provenance';sourceTreeSha256=$tree};Write-Json -LiteralPath $provenancePath -Value $provenance;$sha=Get-Sha $provenancePath
    $ready=&$dashboard -Distribution $distribution -ExpectedVersion '0.7.9' -ProvenancePath $provenancePath -ExpectedProvenanceSha256 $sha -AllowedProvenanceRoot $tempRoot -ReferenceTimeUtc ([datetimeoffset]'2026-09-06T10:30:00Z') -NoThrow
    Assert-True ($ready.State-eq'READY'-and$ready.Passed-and$ready.Stages.Declared-eq'DECLARED'-and$ready.Stages.Found-eq'FOUND'-and$ready.Stages.Validated-eq'VALIDATED') "Healthy release was not READY. State=$($ready.State); gates=$($ready.FailedGates-join', ')."
    Assert-True (-not$ready.WritePerformed-and-not$ready.ExecutionPerformed-and-not$ready.TransportPerformed) 'Dashboard reported an effect.'
    $json1=&$dashboard -Distribution $distribution -ExpectedVersion '0.7.9' -ProvenancePath $provenancePath -ExpectedProvenanceSha256 $sha -AllowedProvenanceRoot $tempRoot -ReferenceTimeUtc ([datetimeoffset]'2026-09-06T10:30:00Z') -NoThrow -AsJson;$json2=&$dashboard -Distribution $distribution -ExpectedVersion '0.7.9' -ProvenancePath $provenancePath -ExpectedProvenanceSha256 $sha -AllowedProvenanceRoot $tempRoot -ReferenceTimeUtc ([datetimeoffset]'2026-09-06T10:30:00Z') -NoThrow -AsJson;Assert-True (($json1-join"`n")-ceq($json2-join"`n")) 'Frozen dashboard JSON was not deterministic.'
    $hashDrift=&$dashboard -Distribution $distribution -ExpectedVersion '0.7.9' -ProvenancePath $provenancePath -ExpectedProvenanceSha256 ('f'*64) -AllowedProvenanceRoot $tempRoot -NoThrow;Assert-True ($hashDrift.State-eq'CONFLICT') 'Provenance hash drift was not CONFLICT.';Assert-GatesExactly $hashDrift @('ReleaseProvenanceSha256') 'Provenance hash gate changed.'
    $missingPath=Join-Path $tempRoot 'missing.json';$missing=&$dashboard -Distribution $distribution -ExpectedVersion '0.7.9' -ProvenancePath $missingPath -ExpectedProvenanceSha256 ('f'*64) -AllowedProvenanceRoot $tempRoot -NoThrow;Assert-True ($missing.State-eq'UNKNOWN') 'Missing provenance was not UNKNOWN.';Assert-GatesExactly $missing @('ReleaseProvenancePresent') 'Missing provenance gate changed.'
    $wrongVersion=($provenance|ConvertTo-Json -Depth 10|ConvertFrom-Json);$wrongVersion.pluginVersion='0.8.0';$wrongVersionPath=Join-Path $tempRoot 'wrong-version.json';Write-Json $wrongVersionPath $wrongVersion;$wrongVersionResult=&$dashboard -Distribution $distribution -ExpectedVersion '0.7.9' -ProvenancePath $wrongVersionPath -ExpectedProvenanceSha256 (Get-Sha $wrongVersionPath) -AllowedProvenanceRoot $tempRoot -NoThrow;Assert-GatesExactly $wrongVersionResult @('ReleaseVersion') 'Release version gate changed.'
    $outside=&$dashboard -Distribution $distribution -ExpectedVersion '0.7.9' -ProvenancePath $dashboard -ExpectedProvenanceSha256 (Get-Sha $dashboard) -AllowedProvenanceRoot $tempRoot -NoThrow;Assert-True ($outside.State-eq'CONFLICT') 'Outside provenance was not CONFLICT.';Assert-GatesExactly $outside @('ReleaseProvenanceWithinRoot') 'Outside-root gate changed.'
    $missingSource=&$dashboard -Distribution ([pscustomobject]@{Name='personal';SourcePath=(Join-Path $tempRoot 'absent');CachePath=$cache}) -ExpectedVersion '0.7.9' -ProvenancePath $provenancePath -ExpectedProvenanceSha256 $sha -AllowedProvenanceRoot $tempRoot -NoThrow;Assert-True ($missingSource.State-eq'UNKNOWN') 'Missing source was not UNKNOWN.';Assert-GatesExactly $missingSource @('DistributionSourceExists') 'Health gate propagation changed.'
    [IO.File]::WriteAllText((Join-Path $cache 'scripts\fixture.ps1'),"'drift'",$utf8);$treeDrift=&$dashboard -Distribution $distribution -ExpectedVersion '0.7.9' -ProvenancePath $provenancePath -ExpectedProvenanceSha256 $sha -AllowedProvenanceRoot $tempRoot -NoThrow;Assert-True ($treeDrift.State-eq'CONFLICT') 'Tree drift was not CONFLICT.';Assert-GatesExactly $treeDrift @('DistributionTreeIdentity') 'Tree drift gate changed.'
}finally{if(Test-Path -LiteralPath $tempRoot){Remove-Item -LiteralPath $tempRoot -Recurse -Force}}
'PowerShell Workbench status dashboard contracts passed.'
