[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter(Mandatory)][string[]]$TemplatePath,
    [Parameter(Mandatory)][string]$OutputPath,
    [Parameter(Mandatory)][string]$ProjectRoot,
    [Alias('Write')][switch]$WriteOutput,
    [switch]$Force
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

function Get-Sha256Text {
    param([AllowEmptyString()][string]$Text)
    $algorithm = [Security.Cryptography.SHA256]::Create()
    try {
        $bytes = (New-Object Text.UTF8Encoding($false)).GetBytes($Text)
        ([BitConverter]::ToString($algorithm.ComputeHash($bytes))).Replace('-', '').ToLowerInvariant()
    } finally { $algorithm.Dispose() }
}

function Add-Gate {
    param([Collections.Generic.List[string]]$List,[string]$Gate)
    if (-not $List.Contains($Gate)) { [void]$List.Add($Gate) }
}

$resolvedRoot = [IO.Path]::GetFullPath($ProjectRoot)
$failedGates = New-Object 'System.Collections.Generic.List[string]'
$fragments = New-Object System.Collections.Generic.List[object]
$seen = @{}
foreach ($path in @($TemplatePath)) {
    $resolvedTemplate = [IO.Path]::GetFullPath($path)
    if (-not (Test-Path -LiteralPath $resolvedTemplate -PathType Leaf)) { Add-Gate -List $failedGates -Gate 'TemplateExists'; continue }
    try { $template = Get-Content -LiteralPath $resolvedTemplate -Raw | ConvertFrom-Json } catch { Add-Gate -List $failedGates -Gate 'TemplateJson'; continue }
    if ([string]$template.schemaVersion -ne '1.0' -or [string]$template.artifactKind -ne 'PowerShellWorkbenchFragmentTemplate') { Add-Gate -List $failedGates -Gate 'TemplateIdentity'; continue }
    if (@($template.failedGates).Count -gt 0) { Add-Gate -List $failedGates -Gate 'TemplateFailedGates'; continue }
    $relative = [string]$template.source.relativePath
    if ([string]::IsNullOrWhiteSpace($relative) -or [IO.Path]::IsPathRooted($relative) -or $relative -match '(^|[\\/])\.\.([\\/]|$)') { Add-Gate -List $failedGates -Gate 'SourceRelativePath'; continue }
    $sourcePath = [IO.Path]::GetFullPath((Join-Path $resolvedRoot $relative.Replace('/','\')))
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) { Add-Gate -List $failedGates -Gate 'SourceExists'; continue }
    $actualSourceSha = (Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($actualSourceSha -cne ([string]$template.source.sha256).ToLowerInvariant()) { Add-Gate -List $failedGates -Gate 'SourceSha256'; continue }
    foreach ($fragment in @($template.fragments)) {
        $kind = [string]$fragment.kind
        $name = [string]$fragment.name
        $text = [string]$fragment.text
        $hash = Get-Sha256Text -Text $text.TrimEnd()
        if ($hash -cne ([string]$fragment.sha256).ToLowerInvariant()) { Add-Gate -List $failedGates -Gate 'FragmentSha256'; continue }
        $key = ($kind + ':' + $name).ToLowerInvariant()
        if ($seen.ContainsKey($key)) {
            if ($seen[$key] -cne $hash) { Add-Gate -List $failedGates -Gate 'DuplicateFragmentConflict' }
            continue
        }
        $seen[$key] = $hash
        [void]$fragments.Add([pscustomobject][ordered]@{ kind=$kind; name=$name; sha256=$hash; text=$text.TrimEnd() })
    }
}

if ($fragments.Count -eq 0) { Add-Gate -List $failedGates -Gate 'FragmentSelected' }
$fragmentArray = @($fragments.ToArray())
$failedGateArray = @($failedGates.ToArray())
$content = @(
    '# Generated by PowerShell Workbench fragment composer.',
    '# Review before execution; generation performs no execution.',
    ''
)
foreach ($fragment in $fragmentArray) {
    $content += "# fragment: $($fragment.kind) $($fragment.name) sha256=$($fragment.sha256)"
    $content += [string]$fragment.text
    $content += ''
}
$scriptText = (@($content) -join "`n").TrimEnd() + "`n"
$tokens = $null
$parseErrors = $null
[void][Management.Automation.Language.Parser]::ParseInput($scriptText,[ref]$tokens,[ref]$parseErrors)
if (@($parseErrors).Count -gt 0) { Add-Gate -List $failedGates -Gate 'ComposedScriptParses' }

$resolvedOutput = [IO.Path]::GetFullPath($OutputPath)
$state = if ($failedGates.Count -eq 0) { if ($WriteOutput) { 'READY_TO_WRITE' } else { 'PREVIEW' } } else { 'BLOCKED' }
if ($WriteOutput -and $failedGates.Count -eq 0) {
    if ((Test-Path -LiteralPath $resolvedOutput) -and -not $Force) { throw 'OutputPath already exists. Use -Force to replace it.' }
    if ($PSCmdlet.ShouldProcess($resolvedOutput, 'Write composed PowerShell script')) {
        $parent = Split-Path -Parent $resolvedOutput
        if (-not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
        [IO.File]::WriteAllText($resolvedOutput, $scriptText, (New-Object Text.UTF8Encoding($false)))
        $state = 'SUCCEEDED'
    }
}

[pscustomobject][ordered]@{ schemaVersion='1.0'; state=$state; outputPath=$resolvedOutput; fragmentCount=$fragments.Count; contentSha256=Get-Sha256Text -Text $scriptText; failedGates=$failedGateArray; writePerformed=($state -eq 'SUCCEEDED'); executionPerformed=$false; transportPerformed=$false }
